namespace RaSetMaker.Models
{
    public enum RomMatcherType
    {
        Null,
        Md5,
        FileNameHash,
        ThreeDO,
        Arduboy,
        Atari7800,
        AtariJaguarCD,
        AtariLynx,
        PcEngine,
        PcEngineCD,
        PcFx,
        GameCube,
        Nintendo64,
        NintendoDS,
        Nes,
        Snes,
        NeoGeoCD,
        Dreamcast,
        Saturn,
        SegaCD,
        Ps1,
        Ps2,
        Psp
    }
}
